pages:
  stage: deploy
  script:
  # Evidently it's faster to copy everything and delete what we don't need 
  # than it is to just copy what we need...
  - mkdir .public
  - cp -r css fonts img js player opponents index.html config.xml .public
  - find .public/opponents -type f ! \( -iname "*.png" -o -iname "*.gif" -o -iname "*.jpg" -o -iname "*.xml" \) -delete
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
