pages:
  stage: deploy
  script:
  - mkdir .public1
  - mkdir .public2
  - cp -r * .public1
  - rsync -avz --exclude 'saves/*.txt' .public1 .public2
  - mv .public2 public
  artifacts:
    paths:
    - public
  only:
  - master