stages:
    - deploy
    - bundle

deploy_production:
    stage: deploy
    tags:
        - production
    script:
        - bash ./prepare-online.sh
        - rsync -rltz --delete .public/ /opt/spnati
    environment:
        name: production
        url: https://spnati.net/
    only:
        - master@spnati/spnati

bundle_offline_package:
    stage: bundle
    tags:
        - production
    script:
        - zip -qr spnati-offline.zip ./ -x .git
        - cp ./spnati-offline.zip /opt/spnati
    only:
        - master@spnati/spnati
        
bundle_online_package:
    stage: bundle
    tags:
        - production
    script:
        - bash ./prepare-online.sh
        - zip -qr spnati-online.zip ./.public
        - cp ./spnati-online.zip /opt/spnati
    only:
        - master@spnati/spnati