deploy_testing:
    stage: deploy
    tags:
        - testing
    script:
        - bash ./prepare-online.sh
        - mkdir -p /opt/spnati-testing/$CI_COMMIT_REF_NAME
        - rsync -rltz --delete .public/ /opt/spnati-testing/$CI_COMMIT_REF_NAME
    when: manual
    environment:
        name: testing/$CI_COMMIT_REF_NAME
        url: https://spnati-testing.faraway-vision.io/$CI_COMMIT_REF_NAME

deploy_production:
    stage: deploy
    tags:
        - production
    script:
        - bash ./prepare-online.sh
        - rsync -rltz --delete .public/ /opt/spnati
    environment:
        # Change to 'production' and https://spnati.net if/when we switch over
        name: staging
        url: https://spnati-staging.faraway-vision.io/
    only:
        - master
