pages:
  stage: deploy
  script:
  # tar may be the easiest way to copy an arbitrary
  # list of files, keeping the directory structure.
  # Include *.js and *.css to accomodate Monika.
  - cp -r css fonts img js player index.html config.xml .public
  - find `python opponents/list_opponents.py` -iname "*.png" -o -iname "*.gif" -o -iname "*.jpg" -o -iname "*.xml" -o -iname "*.js" -o -iname "*.css" | tar -cT - | tar -C .public -x
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
