deploy_testing:
    stage: deploy
    tags:
        - testing
    script:
        - bash ./prepare-online.sh
        - mkdir -p "/mnt/disks/data/spnati-testing-environments/${CI_ENVIRONMENT_SLUG}"
        - rsync -rltz --delete .public/ "/mnt/disks/data/spnati-testing-environments/${CI_ENVIRONMENT_SLUG}"
    when: manual
    environment:
        name: testing/$CI_COMMIT_REF_NAME
        url: https://spnati.faraway-vision.io/test/$CI_ENVIRONMENT_SLUG
        on_stop: cleanup_testing
    only:
        - merge_requests

cleanup_testing:
    stage: deploy
    tags:
        - testing
    variables:
        GIT_STRATEGY: none
    script:
        - rm -rf "/mnt/disks/data/spnati-testing-environments/${CI_ENVIRONMENT_SLUG}"
    when: manual
    environment:
        name: testing/$CI_COMMIT_REF_NAME
        action: stop
        
deploy_production:
    stage: deploy
    tags:
        - production
    script:
        - bash ./prepare-online.sh
        - rsync -rltz --delete .public/ /opt/spnati
    environment:
        # Change to 'production' and https://spnati.net if/when we switch over
        name: production
        url: https://spnati.net/
    only:
        - master
